# SAST pipeline
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Security static source code analysis@2019
  inputs:
    CheckmarxService: 'AWS CX 8.9 HF 5'
    projectName: 'CxWebgoat - .NET'
    preset: 'High and Medium'
    fullTeamName: 'CxServer'
    incScan: false
    denyProject: true
    high: '1'
    medium: '5'
    low: '10'